class_name PlayerVisuals
extends AnimatedSprite2D
## Drives the silhouette skater sheet from the controller's state machine.
## Placeholder art pipeline: the sheet is generated by
## `game/tools/gen_skater_sheet.py`; when commissioned/AI frames arrive, keep
## the same grid + ANIMS table and this script needs no changes.
##
## Owns presentation only — reads PlayerController state, never writes it.
## Also owns the contact FX (push dust, landing dust, grind sparks, slide
## dust), built in code so the scene file stays minimal.

const SHEET := "res://assets/player/skater_sheet.png"
const FRAME := Vector2i(44, 44)
const COLS := 8
## Sheet is 1x logical pixels; drawn at this scale with nearest filtering.
const DRAW_SCALE := 2.0
## Texture-space Y offset that puts the wheels on the collision capsule's
## bottom (see gen_skater_sheet.py baseline note).
const FOOT_OFFSET := -7.0

const ANIMS := {
	"roll":    {"frames": [0, 1], "fps": 4.0, "loop": true},
	"push":    {"frames": [2, 3, 4], "fps": 10.0, "loop": false},
	"crouch":  {"frames": [5], "fps": 1.0, "loop": true},
	"air":     {"frames": [6], "fps": 1.0, "loop": true},
	"land":    {"frames": [7], "fps": 1.0, "loop": true},
	"grind":   {"frames": [8], "fps": 1.0, "loop": true},
	"bail":    {"frames": [9], "fps": 1.0, "loop": true},
	"recover": {"frames": [10], "fps": 1.0, "loop": true},
	"walk":    {"frames": [11, 12, 13, 14], "fps": 7.0, "loop": true},
	"stand":   {"frames": [15, 16], "fps": 1.6, "loop": true},
	"crawl":   {"frames": [17, 18], "fps": 6.0, "loop": true},
	"climb":   {"frames": [19, 20], "fps": 5.0, "loop": true},
}

@export_group("Juice")
## Squash on touchdown / stretch on ollie, recovered at squash_recover per sec.
@export var land_squash := Vector2(1.22, 0.78)
@export var ollie_stretch := Vector2(0.84, 1.16)
@export var squash_recover := 9.0
## How long the landing pose holds before rolling resumes.
@export var land_pose_time := 0.14
## Landing speed (px/s) under which the squash+dust are skipped.
@export var land_fx_min_speed := 120.0

var _player: PlayerController
var _squash := Vector2.ONE
var _land_hold := 0.0
var _push_playing := false

var _push_dust: CPUParticles2D
var _land_dust: CPUParticles2D
var _grind_sparks: CPUParticles2D
var _slide_dust: CPUParticles2D


func _ready() -> void:
	_player = owner as PlayerController
	texture_filter = TEXTURE_FILTER_NEAREST
	offset = Vector2(0.0, FOOT_OFFSET)
	_build_frames()
	_build_fx()
	if _player != null:
		_player.state_changed.connect(_on_state_changed)
		if _player.has_signal("pushed"):
			_player.pushed.connect(_on_pushed)
	animation_finished.connect(_on_animation_finished)
	play("roll")


func _physics_process(delta: float) -> void:
	if _player == null:
		return
	_land_hold = maxf(_land_hold - delta, 0.0)
	_squash = _squash.lerp(Vector2.ONE, 1.0 - exp(-squash_recover * delta))
	scale = Vector2(DRAW_SCALE, DRAW_SCALE) * _squash
	_set_anim(_pick_anim())
	_scale_anim_speed()
	_grind_sparks.emitting = _player.state == SkateState.GRINDING \
			and absf(_player.velocity.length()) > 60.0
	_slide_dust.emitting = _player.state == SkateState.POWERSLIDING


func _scale_anim_speed() -> void:
	# Crawl/climb cycles track actual movement so the player never moonwalks
	# in place; everything else runs at authored fps.
	match animation:
		&"crawl":
			speed_scale = clampf(
				absf(_player.velocity.x) / maxf(_player.tuning.crawl_speed, 1.0),
				0.0, 1.2)
		&"climb":
			speed_scale = clampf(
				_player.velocity.length() / maxf(_player.tuning.climb_speed, 1.0),
				0.0, 1.2)
		_:
			speed_scale = 1.0


func _pick_anim() -> String:
	match _player.state:
		SkateState.SKATING:
			if _land_hold > 0.0:
				return "land"
			if _push_playing:
				return "push"
			return "roll"
		SkateState.CROUCHING, SkateState.POWERSLIDING:
			return "crouch"
		SkateState.AIRBORNE:
			return "air"
		SkateState.GRINDING:
			return "grind"
		SkateState.BAILING:
			return "bail"
		SkateState.RECOVERING:
			return "recover"
		SkateState.ON_FOOT:
			return "walk" if absf(_player.velocity.x) > 20.0 else "stand"
		SkateState.CRAWLING:
			return "crawl"
		SkateState.CLIMBING:
			return "climb"
		SkateState.INTERACTING:
			return "stand" if _player.velocity.length() < 20.0 else "roll"
	return "roll"


func _set_anim(anim: String) -> void:
	if animation != anim:
		play(anim)


func _on_state_changed(previous: int, current: int) -> void:
	if previous == SkateState.AIRBORNE and current == SkateState.SKATING:
		if _player.last_landing_speed_in >= land_fx_min_speed:
			_squash = land_squash
			_land_hold = land_pose_time
			_land_dust.restart()
	elif current == SkateState.AIRBORNE \
			and previous in [SkateState.SKATING, SkateState.CROUCHING]:
		_squash = ollie_stretch
	if current != SkateState.SKATING:
		_push_playing = false


func _on_pushed() -> void:
	_push_playing = true
	play("push")
	_push_dust.restart()


func _on_animation_finished() -> void:
	if animation == "push":
		_push_playing = false


# --- Setup -------------------------------------------------------------------


func _build_frames() -> void:
	var tex: Texture2D = load(SHEET)
	var frames := SpriteFrames.new()
	frames.remove_animation("default")
	for anim_name: String in ANIMS:
		var def: Dictionary = ANIMS[anim_name]
		frames.add_animation(anim_name)
		frames.set_animation_speed(anim_name, def["fps"])
		frames.set_animation_loop(anim_name, def["loop"])
		for idx: int in def["frames"]:
			var at := AtlasTexture.new()
			at.atlas = tex
			at.region = Rect2(
				(idx % COLS) * FRAME.x, (idx / COLS) * FRAME.y,
				FRAME.x, FRAME.y)
			frames.add_frame(anim_name, at)
	sprite_frames = frames


func _build_fx() -> void:
	# Parented to Visual so facing flips and slope rotation carry into the
	# emit direction; local_coords stays off so trails hang in the world.
	_push_dust = _make_burst(6, 0.45, Vector2(-14, 24), Vector2(-1, -0.2),
			Color(0.78, 0.75, 0.68, 0.55))
	_land_dust = _make_burst(12, 0.55, Vector2(0, 26), Vector2(0, -0.4),
			Color(0.78, 0.75, 0.68, 0.5))
	_land_dust.spread = 85.0
	_grind_sparks = _make_stream(14, 0.3, Vector2(0, 26),
			Color(1.0, 0.72, 0.3, 0.9))
	_slide_dust = _make_stream(10, 0.6, Vector2(-10, 24),
			Color(0.7, 0.68, 0.62, 0.4))
	_slide_dust.scale_amount_max = 3.0


func _make_burst(amount: int, life: float, pos: Vector2, dir: Vector2,
		tint: Color) -> CPUParticles2D:
	var p := _base_particles(amount, life, pos, tint)
	p.one_shot = true
	p.explosiveness = 1.0
	p.emitting = false
	p.direction = dir
	p.spread = 35.0
	p.initial_velocity_min = 40.0
	p.initial_velocity_max = 110.0
	p.gravity = Vector2(0, -30)
	return p


func _make_stream(amount: int, life: float, pos: Vector2,
		tint: Color) -> CPUParticles2D:
	var p := _base_particles(amount, life, pos, tint)
	p.emitting = false
	p.direction = Vector2(-1, -0.3)
	p.spread = 25.0
	p.initial_velocity_min = 60.0
	p.initial_velocity_max = 160.0
	p.gravity = Vector2(0, 220)
	return p


func _base_particles(amount: int, life: float, pos: Vector2,
		tint: Color) -> CPUParticles2D:
	var p := CPUParticles2D.new()
	p.amount = amount
	p.lifetime = life
	p.position = pos
	p.color = tint
	p.local_coords = false
	p.scale_amount_min = 1.5
	p.scale_amount_max = 2.5
	p.z_index = 4
	get_parent().add_child(p)
	return p
